name: CI

on:
  push:
    branches:
      - "*"

  pull_request:
    types: [opened, synchronize]
    branches:
      - "main"

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version: ["3.8", "3.9", "3.10"]
        os: ["ubuntu-latest", "windows-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      # Allow debugging with tmate
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true

      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-root

      - name: Install poetry
        if: steps.cache.outputs.cache-hit != 'true'
        # TODO: remove python -m pip install --force git+https://github.com/python-poetry/poetry-core.git@ad33bc2
        # once there's a release of Poetry 1.2.x including poetry-core > 1.1.0a6
        # Ref: https://github.com/python-poetry/poetry-core/pull/188
        # python -m pip install --force git+https://github.com/python-poetry/poetry-core.git@ad33bc2
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry==1.2.0b3"
          python -m poetry plugin add poetry-version-plugin
      - name: Configure poetry
        run: python -m poetry config virtualenvs.create false

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: python -m poetry install

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Upload coverage
        uses: codecov/codecov-action@v2
