name: Build Docs

on:
  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure workflow
        id: branch_name
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'

      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure poetry
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install "poetry==1.2.0b3"

          poetry config virtualenvs.in-project true          

      - name: Install Package Dependencies
        run: poetry install

      - name: Create version and Publish to gh-pages
        run: |
          poetry run mike deploy --push $(poetry version -s)
